name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.16
      - name: npm install, build and test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          npm install
          npm run build
          npm test
        env:
          CI: true
